### ISSUE TITLE
High numbers on iOS?

### ISSUE THREAD

**Issue by pfulop** [oblador/react-native-performance#68]
We are currently using this library to determine which part of the app is currently the slowest to load. One thing we noticed are high numbers for measuring `nativeLaunchEnd` relative to `nativeLaunchStart` on ios. For instance, we see 340756159ms which translated to almost 4 days. This would mean the app is taking 4 days to start. Are there some cases where this can happen and how to prevent them? This is currently polluting our measurements.

**Comment by oblador** [comment]
Are you seeing this in development or real user monitoring? If the latter is it possible that it's related to users backgrounding the app during startup?

**Comment by pfulop** [comment]
This is in production.

> If the latter is it possible that it's related to users backgrounding the app during startup?

I would not expect days in that case but max hours. I would expect ios clearing that process within a day.

**Comment by gavrix** [comment]
Was seeing this too in RN 0.68.2 Which I believe was fixed in https://github.com/facebook/react-native/pull/33983 and is not reproducible in 0.68.9 anymore.

The issue I believe is in difference of "now" primitives used by react-native-performance and by RN runtime itself. 
`RNPerformanceGetTimestamp` uses `std::chrono::steady_clock::now()` while RN used `std::chrono::system_clock::now()`.

I believe, with this context the issue can be closed.

**Comment by oblador** [comment]
Closing this as it should have been fixed in [5.0.0](https://github.com/oblador/react-native-performance/releases/tag/v5.0.0), please open a new issue if it persists.
