### ISSUE TITLE
[Question] Maybe we could somehow make use of react-native implementation?

### ISSUE THREAD

**Issue by Szymon20000** [oblador/react-native-performance#93]
https://github.com/facebook/react-native/blob/f4e56fdf1946d2e54d8db7b445df001cf6ebfdb0/Libraries/WebPerformance/NativePerformance.cpp

**Comment by oblador** [comment]
Could you elaborate a bit?

**Comment by Szymon20000** [comment]
I just saw that someone from React Native team implemented Web Performance API. Just like you but it's a turbo module and it missing a lot of features thet your library expose. For instance Flipper plugin or a lot of native marks. 
I just though that maybe this library could make use of RN implementation so it's easier for you to maintain

**Comment by oblador** [comment]
Hmm, maybe but probably not. I have previous bad experience on relying on RN core perf stuff because it seems only FB rely on them so they break in bad ways from time to time. It looks pretty bare bones, and also it would be a breaking change for users and be tied to RN version. 

Fwiw, this package is also built for new arch (one of the first packages to do so even).

**Comment by oblador** [comment]
Are you at the conf with @mrousavy btw? Maybe we can discuss in person and would love to hear your usecases 😄

**Comment by Szymon20000** [comment]
Unfortunately, I am tied to Poland for a few months :)
I just wanted to draw your attention to the fact that RN has partially implemented a similar thing in case it is somehow useful to you. I often use your library and it is very helpful :)
